### ISSUE TITLE
duplicate key error collection: test.users index: uid_1 dup key: { : null }

### ISSUE THREAD

**Issue by khase** [h-da/geli#155]
You can only register one Teacher through the register-form.

```
MongoError: E11000 duplicate key error collection: test.users index: uid_1 dup key: { : null }
    at Function.MongoError.create (/usr/src/app/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/usr/src/app/node_modules/mongodb/lib/utils.js:139:22)
    at /usr/src/app/node_modules/mongodb/lib/collection.js:669:23
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:120:56)
    at /usr/src/app/node_modules/mongodb/lib/bulk/unordered.js:465:9
    at handleCallback (/usr/src/app/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/usr/src/app/node_modules/mongodb/lib/bulk/unordered.js:413:5)
    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

we need to remove the unique modifier from the uid (aka. Matrikelnummer)
```
    uid: {
      type: String,
      lowercase: true,
      unique: true,
      sparse: true
    },
```

or a teacher needs to submit a alternative unique "Matrikelnummer"

**Comment by grosspersky** [comment]
Fixed with #156
