### ISSUE TITLE
Duplicating a lecture does not duplicate the contained material

### ISSUE THREAD

**Issue by d89** [h-da/geli#183]
Duplicating a lecture does not duplicate the units within the duplicated lecture

**Comment by d89** [comment]
Pretty nice! I have not done an extensive test but from what I duplicated, everything works as exepcted 👍

**Comment by d89** [comment]
Oops, just found an occurrence where it did not work:

![image](https://user-images.githubusercontent.com/423154/33341319-f04173b4-d47e-11e7-8a3f-50d518d3650f.png)

`{"name":"InternalServerError","message":"Failed to duplicate lecture","stack":"Error\n    at InternalServerError.HttpError [as constructor] (/usr/src/app/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new InternalServerError (/usr/src/app/node_modules/routing-controllers/http-error/InternalServerError.js:20:28)\n    at DuplicationController.<anonymous> (/usr/src/app/controllers/DuplicationController.js:54:34)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/controllers/DuplicationController.js:17:65)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)\nCaused by: Cannot read property 'exportJSON' of null\nTypeError: Cannot read property 'exportJSON' of null\n    at Unit_1.Unit.findById.then (/usr/src/app/models/Lecture.js:61:29)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}`

**Comment by grosspersky** [comment]
Duplication doesn't notify if it has been successfully completed.

**Comment by d89** [comment]
Added in the session on 2017-11-30:

- [ ] Forward to the course that has just been duplicated

**Comment by lukaskorte** [comment]
@khase, @alexweinfurter what is the status of this issue?

**Comment by khase** [comment]
Should be fixed with #419.
Can't validate this right now.
