### ISSUE TITLE
When uploading a picture as admin for another user, I am logged out

### ISSUE THREAD

**Issue by d89** [h-da/geli#450]
When I upload a picture for another user as administrator, I am either logged out afterwards or even logged in as the user I just uploaded a picture for.

**Comment by d89** [comment]
I am not logged out any longer, but the picture is not changed when I upload another one for a user as admin.

**Comment by d89** [comment]
Still happens to me, see this gif showing myself as admin trying to upload a picture for @grosspersky 

![test](https://user-images.githubusercontent.com/423154/35242225-4154f0cc-ffb9-11e7-9146-30ac2f46e688.gif)

This is the error I get shown here:

![image](https://user-images.githubusercontent.com/423154/35242273-60eac132-ffb9-11e7-80a5-48b2f36fab2e.png)

```
{"name":"ForbiddenError","stack":"Error\n    at ForbiddenError.HttpError [as constructor] (/usr/src/app/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new ForbiddenError (/usr/src/app/node_modules/routing-controllers/http-error/ForbiddenError.js:20:28)\n    at ReportController.<anonymous> (/usr/src/app/controllers/ReportController.js:184:23)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/controllers/ReportController.js:19:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/controllers/ReportController.js:15:12)\n    at ReportController.getUserProgress (/usr/src/app/controllers/ReportController.js:182:16)\n    at ActionMetadata.callMethod (/usr/src/app/node_modules/routing-controllers/metadata/ActionMetadata.js:108:48)\n    at /usr/src/app/node_modules/routing-controllers/RoutingControllers.js:92:140\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}
```

**Comment by AndreasSchroll** [comment]
#504
